name: boutRight
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens
  - blas
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - comm
  - cudatoolkit        # Automatically install the correct version based on the system
  - cudnn              # Automatically resolve the correct version
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - expat
  - filelock
  - fontconfig
  - freetype
  - git
  - glib
  - glib-tools
  - gst-plugins-base
  - gstreamer
  - h2
  - hpack
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - jupyter_client
  - jupyter_core
  - krb5
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libclang13
  - libdeflate
  - libexpat
  - libffi
  - libglib
  - libhwloc
  - libiconv
  - libintl
  - libintl-devel
  - libjpeg-turbo
  - liblapack
  - libogg
  - libpng
  - libsodium
  - libsqlite
  - libtiff
  - libuv
  - libvorbis
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - libzlib
  - libzlib-wapi
  - lxml
  - markupsafe
  - matplotlib-inline
  - matplotlib>=3.3.0
  - mkl
  - mpmath
  - msys2-conda-epoch
  - nest-asyncio
  - networkx
  - numpy
  - openjpeg
  - openssl
  - packaging
  - parso
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - ply
  - prompt-toolkit
  - psutil
  - pytorch          # Automatically install the correct version based on the system
  - torchaudio       # Automatically install the correct version based on the system
  - torchvision      # Automatically install the correct version based on the system
  - tqdm
  - scikit-learn
  - pandas
  - opencv
  - ultralytics
